# Generated by Django 4.1.13 on 2023-12-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(default='', max_length=70)),
                ('createdDay', models.IntegerField(default=1)),
                ('createdMonth', models.IntegerField(default=1)),
                ('createdYear', models.IntegerField(default=2022)),
                ('createdAt', models.DateTimeField(default=2022, max_length=200)),
                ('firstName', models.CharField(default='', max_length=70)),
                ('lastName', models.CharField(default='', max_length=70)),
                ('phoneNumber', models.CharField(default='', max_length=70)),
                ('emailAddress', models.CharField(default='', max_length=70)),
                ('countryCode', models.CharField(default='', max_length=70)),
                ('maritalStatus', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=70)),
                ('dateOfBirth', models.CharField(default='', max_length=70)),
                ('userType', models.CharField(default='', max_length=70)),
                ('isDeleted', models.BooleanField(default=False)),
                ('stateOfResidence', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('nOKFullName', models.CharField(default='', max_length=70)),
                ('nOKRelationship', models.CharField(default='', max_length=70)),
                ('nOKEmailAddress', models.CharField(default='', max_length=70)),
                ('nOKPhoneNumber', models.CharField(default='', max_length=70)),
                ('nOKAddress', models.CharField(default='', max_length=250)),
                ('pin', models.IntegerField(default='')),
                ('password', models.CharField(default='', max_length=250)),
                ('fileUrl', models.TextField(default='')),
                ('fileName', models.TextField(default='')),
                ('originalFileName', models.TextField(default='')),
            ],
        ),
    ]
