# Generated by Django 4.1.13 on 2023-12-22 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 9, 46, 6, 187807)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
