# Generated by Django 4.1.13 on 2023-12-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_id', models.CharField(default='', max_length=250)),
                ('network', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('amount', models.CharField(default='', max_length=70)),
                ('cable_tv', models.CharField(default='', max_length=70)),
                ('subscription_plan', models.CharField(default='', max_length=70)),
                ('smartcard_number', models.CharField(default='', max_length=70)),
                ('amount_charged', models.CharField(default='', max_length=70)),
                ('electricity', models.CharField(default='', max_length=70)),
                ('service_fee', models.CharField(default='', max_length=70)),
                ('meter_number', models.CharField(default='', max_length=70)),
                ('token', models.CharField(default='', max_length=70)),
                ('units', models.CharField(default='', max_length=70)),
                ('order_id', models.CharField(default='', max_length=70)),
                ('service_id', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(default='', max_length=70)),
                ('createdAt', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='', max_length=70)),
                ('code', models.CharField(default='', max_length=70)),
                ('message', models.CharField(default='', max_length=70)),
                ('status', models.CharField(default='', max_length=70)),
                ('previous', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('serviceType', models.CharField(default='', max_length=70)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiondata')),
            ],
        ),
    ]
